//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serCompras.Views
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sercomprasEntities : DbContext
    {
        public sercomprasEntities()
            : base("name=sercomprasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<provider> providers { get; set; }
        public virtual DbSet<budget> budgets { get; set; }
        public virtual DbSet<budget_detail> budget_detail { get; set; }
        public virtual DbSet<request_detail> request_detail { get; set; }
        public virtual DbSet<request_provider> request_provider { get; set; }
        public virtual DbSet<request> requests { get; set; }
        public virtual DbSet<document> documents { get; set; }
    }
}
