//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serCompras.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class provider
    {
        public int id { get; set; }
        public Nullable<int> id_user { get; set; }
        public string legal_name { get; set; }
        public string rut { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<byte> status { get; set; }
    }
}
