//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serCompras.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class request_provider
    {
        public int id { get; set; }
        public Nullable<int> id_provider { get; set; }
        public Nullable<int> id_request { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
